### ISSUE TITLE
Running in child processes even on single process

### ISSUE THREAD

**Issue by christian-kolb** [webmozarts/console-parallelization#14]
@webmozart I have a process with many items which I can't run in multiple processes. As far as I can see there is no way to spawn child processes for every item, is there? In the steps there is a lot of work done which uses a lot of RAM. With child processes, every data usage would be removed after one run.

Is there any way to trigger the single items within child processes without having multiple processes?

**Comment by theofidry** [comment]
You could alter the code to ensure a child process is used even for `--processes 1` (currently if only 1 thread is found, it will use the current process instead of spawning a child one)

But IIRC, there is the `run{Before,After}Batch()` which can help to clean some state (e.g. clearing the repositories)

**Comment by christian-kolb** [comment]
@theofidry Thanks for the fast reply  🙂
Using the `run{Before,After}Batch()` methods is unfortunately not an option. I'm using the command to run a replay of projections in an EventSourcing system and on execution time don't know which repositories are used within the projection handlers. That's why I thought of the child processes as this would automatically clear all used resources.

With altering the code you mean overwriting `executeMasterProcess`, copying everything over and adapt to always use the child process method? That would have been my backup plan 🙂 But if there is no other way, that I will need to do this. Do you think this would make a useful feature for this package? Something like an optional `--always-use-child-process` argument to trigger this behaviour?

**Comment by theofidry** [comment]
I was more thinking of a PR to change the behaviour to use a child process when giving `--processes 1`. That would be simpler and more consistent than introducing a new option just for this case

**Comment by christian-kolb** [comment]
@theofidry Ah ok, doesn't that change the current behaviour? If someone is using `--processes 1` it it's the same as not setting it. With an update the behaviour would change. I don't know if there is a relevant usage set of users which this configuration.

But I wouldn't mind. If it's ok to you, I would prepare a pull request tomorrow.

**Comment by theofidry** [comment]
Technically it is a BC, but since it's quite an edge and arguably a bug (you do specify a process: why doesn't it spawn a child?) I think it could pass in 1.1.0

**Comment by christian-kolb** [comment]
Great, then I will try to provide a pull request tomorrow. Is it enough to provide an additional test like `test_it_can_run_the_command_with_multiple_processes`?

**Comment by theofidry** [comment]
Yes

**Comment by theofidry** [comment]
Closed by #15
