### ISSUE TITLE
[2.x] Some resources are missing

### ISSUE THREAD

**Issue by llaville** [webmozarts/console-parallelization#180]
Hello,

I've just have a look on this project that seems usefull. As there is a major version v2 under development, I've look on it (branch `main`), and found that some resources are still missing in GitHub repository (for beta 2)

Checks 
- https://github.com/webmozarts/console-parallelization/blob/2.0.0-beta.2/bin/console#L10-L14
- https://github.com/webmozarts/console-parallelization/blob/2.0.0-beta.2/bin/no-framework#L9

Namespaces did not follow Composer PSR-4 structure
- https://github.com/webmozarts/console-parallelization/blob/2.0.0-beta.2/bin/set-composer-conflicts.php#L14
- https://github.com/webmozarts/console-parallelization/blob/2.0.0-beta.2/composer.json#L44-L46

Unable to test it in real condition. Or did I missed something ?

PS: I've tried with following `composer.json` file

```
{
    "require": {
        "webmozarts/console-parallelization": "^2@dev"
    }
}
```

**Comment by llaville** [comment]
**Found origin of issue.**

`composer.json` file identity both the same namespace (see https://github.com/webmozarts/console-parallelization/blob/2.0.0-beta.2/composer.json#L43-L52).
Even if it's allowed, the [.gitattributes](https://github.com/webmozarts/console-parallelization/blob/2.0.0-beta.2/.gitattributes#L8) file in this repository exclude the `tests` folder from release.
So when Composer install the package with default behavior `prefer-install` with `dist` by default, it used the tarball that was built with ignoring tests folder.

Work around is to install package with source distribution like : 
`composer update --prefer-install=source`

**Comment by theofidry** [comment]
Ah indeed, those are more internal (for tests) commands, not really meant for you to use them.

Actually would be best to exclude the bin with `.gitattributes` too.

There is obviously nothing wrong with installing the source to try them as well, but I would argue they might not be the best examples, they are a bit convoluted since it requires a few tweaks to make the final output more stable with various configurations.

**Comment by llaville** [comment]
So I suggest to use the `alpha` stage for your version 2.0.0, and not the `beta` if you really want to follow semantic versioning phylosophy.
In current state, I'll stop to investigate on current develop major version 2, and wait for a stable one !
