### ISSUE TITLE
Error when $_SERVER['PWD'] is not set

### ISSUE THREAD

**Issue by tdierolf** [webmozarts/console-parallelization#204]
Hi. When PWD is not set in der `$_SERVER` vars this error comes up:

```
In ParallelExecutorFactory.php line 437:
  mb_strpos() expects parameter 2 to be string, null given
```
It is caused in this method of class ParallelExecutorFactory:
```
    private static function getScriptPath(): string
    {
        $pwd = $_SERVER['PWD'];
        $scriptName = $_SERVER['SCRIPT_NAME'];

        return 0 === mb_strpos($scriptName, $pwd)
            ? $scriptName
            : $pwd.DIRECTORY_SEPARATOR.$scriptName;
    }
```

Thanks, kind regards!
Tim

**Comment by theofidry** [comment]
Hi thanks for the report!

Would it be possible to have more details about the context of the execution? e.g. platform, OS, PHP version, package version?

**Comment by tdierolf** [comment]
Yes, sure, sorry! :)

Platform: Linux on AWS ec2
OS: Ubuntu 22.04 Server
PHP: 7.4
Package version: 2.1.0
Application: Symfony 4.4

Quick fix for me was adding the PWD to .env within the application.

Cheers!

**Comment by fashxp** [comment]
got the same problem when in docker setup like https://github.com/pimcore/demo/blob/11.x/docker-compose.yaml

**Comment by theofidry** [comment]
Sorry for the delayed response. I'll have to try but I wonder what we can use as an alternative in this scenario then.

**Comment by mohammed-mahmoud-scandi** [comment]
any updates .... @theofidry

**Comment by theofidry** [comment]
Could anyone try #219 see if that fixes your issue?

**Comment by jantom90** [comment]
Hi @theofidry, I tested your PR.
Looks good on Docker, where it gives '/var/www/html' for getcwd and 'bin/console' for $_SERVER['SCRIPT_NAME'].
But, it's different on VPS. There, getcwd returns '/some/storage/vendor/pimcore/pimcore/lib/', and $_SERVER['SCRIPT_NAME'] gives '/some/storage/bin/console'.
We might need an extra check for SCRIPT_NAME.If it's an absolute path, we can just go with that. If not, we can use str_starts_with in the last part of the method.
