### ISSUE TITLE
Bug on Windows systems

### ISSUE THREAD

**Issue by stanislavgoraj** [webmozarts/console-parallelization#24]
On Windows systems an error occurs because PHP_EOL is not "\n" there but "\n\r".

Line 109 \Webmozarts\Console\Parallelization\ProcessLauncher
(instead of "\n" PHP_EOL should be used here)

**Comment by theofidry** [comment]
PR appreciated; unfortunately we don't have any developer developing on Windows so the Windows support is more likely to come from the community than from us :)

**Comment by stanislavgoraj** [comment]
I use webmozarts/console-parallelization on an IIS server. Except for the bug, everything works great - thank you!

**Comment by theofidry** [comment]
This was fixed in #25. I double checked but we do not appear to have another occurrence of `\n` except in a logger which is harmless and will be changed
