### ISSUE TITLE
Symfony 7 compatibility

### ISSUE THREAD

**Issue by DanielCambray** [webmozarts/console-parallelization#289]
Hi, is it possible to make it compatible with Symfony 7.1 ?

There's a PR but it's not merged. Do you need help ?

**Comment by theofidry** [comment]
Apologies for the late reply, somehow I missed it.

It is possible, IIRC there is a few CI tweaks to do to make it green again and then rebase the existing PR

**Comment by tdierolf** [comment]
Symfony 7 compatibility would be highly appreciated since it keeps me from updating my projects.❤️

**Comment by DanielCambray** [comment]
I forked the project, rebase your work on the main branch.
I wanted to test the CI from my repo, but I don't know how.
So I made a PR, but I need your approval.

Can you guide me ?

**Comment by theofidry** [comment]
Thanks for the PR @DanielCambray!

I think the way to go for testing is enabling GitHub Actions on our fork and do a MR against _your_ main branch too: this way you get feedback instantly. You should keep the currently open MR against this repo, but it will require me to approve the execution every single time which ofc is going to be a bit slower

**Comment by theofidry** [comment]
Merged

**Comment by tdierolf** [comment]
Thanks a lot! 🎉 👍
