### ISSUE TITLE
ItemBatchIterator | Implement as Iterable?

### ISSUE THREAD

**Issue by andreas-gruenwald** [webmozarts/console-parallelization#36]
I just stumpled upon your new ItemBatchIterator implementation: https://github.com/webmozarts/console-parallelization/blob/master/src/ItemBatchIterator.php

Actually we use a very similar concept to iterate over various types of files (XML, CSV, Excel, arrays, etc.) and are using PHP's ``Iterable`` and ``Countable`` interfaces.

```php
interface IteratorInterface extends \Iterator, \Countable {
 
}
````

Probably it would be a good idea to also let the ItemBatchIterator implement a similar interface to make the solution very generic and allow multiple types of iterators?

**Comment by theofidry** [comment]
From one of your issues, we might try to support cases where the number of items in unknown so  implementing `Countable` might not be ideal.

It may make sense to implement `Iterator`, but for now the wins are not very clear.

**Comment by andreas-gruenwald** [comment]
> From one of your issues, we might try to support cases where the number of items in unknown so implementing `Countable` might not be ideal.

You are referring #26. The number of items either might be known or unknown (I tried to explain in #26). But you are right, the interface won't work out for an unknown amount of items.

> It may make sense to implement `Iterator`, but for now the wins are not very clear.
Let's close the issue for the moment. I can come back to it in the future after testing the ItemBatchIterator, if still relevant.

**Comment by theofidry** [comment]
This is now part of 2.x so there won't be any issue about changing stuff for a bit :)
